version: '3.9'

services:
  ngrok:
    build:
      dockerfile: Dockerfile
      context: ngrok
    container_name: ngrok
    command: /bin/sh -c "ngrok http golang-server:8090 --region eu & sh -c 'sleep 3 && getaddress > /tmp/newaddr && tail -f /tmp/newaddr'"
  
  example-server:
    build:
      dockerfile: Dockerfile
      context: example-server
    container_name: golang-server
    expose:
      - 8090
    command: go run main.go

  debug:
    build:
      dockerfile: Dockerfile
      context: example-debug
    container_name: debug_container
    command: /bin/bash -c 'sleep 5 && scan "golang-server:8090" && tail -f /tmp/log'